function Fig2ListCtrl($scope) {
    $scope.views    = [{"name":"GFACT", "description":"表示倍率を設定"},
                       {"name":"GAXIS", "description":"全体座標系を表示"},
                       {"name":"AXONOMETRIC", "description":"アクソノメトリック表示"},
                       {"name":"PERSPECTIVE", "description":"パースペクティブ表示"},
                       {"name":"FOCUS", "description":"視点中心を設定"},
                       {"name":"ANGLE", "description":"視点角度の設定"},
                       {"name":"DISTS", "description":"視点サイズを設定"},
                       {"name":"DFACT", "description":"変形倍率を設定"},
                       {"name":"MFACT", "description":"曲げモーメント図の倍率を設定"},
                       {"name":"SHIFT", "description":"ページ上の表示位置を移動"}];
    $scope.elems    = [{"name":"ELEMCODE", "description":"部材番号を表示"},
                       {"name":"EV", "description":"部材の指定した値を表示"},
                       {"name":"HINGE", "description":"部材端ピンを描画"},
                       {"name":"PHINGE", "description":"塑性ヒンジを描画"},
                       {"name":"EAXIS", "description":"部材座標系を描画"},
                       {"name":"DRAW", "description":"断面形状を描画"},
                       {"name":"ALIAS", "description":"断面番号の別名を設定"},
                       {"name":"AREA", "description":"面材の面積を表示"},
                       {"name":"LENGTH", "description":"線材の長さを表示"},
                       {"name":"MAX", "description":"各断面の最大検定比部材を強調表示"}];
    $scope.efilter  = [{"name":"ELEM", "description":"表示する部材タイプを設定"},
                       {"name":"EF", "description":"表示部材を絞り込み"},
                       {"name":"ELEMLAYER", "description":"表示する部材レイヤを設定"},
                       {"name":"SECTION", "description":"表示する断面番号を設定"},
                       {"name":"SECTION-", "description":"表示しない断面番号を設定"},
                       {"name":"X", "description":"表示するX方向範囲を設定"},
                       {"name":"Y", "description":"表示するY方向範囲を設定"},
                       {"name":"Z", "description":"表示するZ方向範囲を設定"},
                       {"name":"X-", "description":"表示しないX方向範囲を設定"},
                       {"name":"Y-", "description":"表示しないY方向範囲を設定"},
                       {"name":"Z-", "description":"表示しないZ方向範囲を設定"},
                       {"name":"PLANE", "description":"指定した平面から一定距離範囲のみ表示"},
                       {"name":"FENCE", "description":"指定した平面を横切る部材のみ表示"},
                       {"name":"CIRCLE", "description":"指定した円の内部の部材のみ表示"},
                       {"name":"RATE", "description":"検定比で表示部材を絞り込み"}];
    $scope.nodes    = [{"name":"NODECODE", "description":"節点番号を表示"},
                       {"name":"NODELAYER", "description":"表示する節点レイヤを設定"},
                       {"name":"CONF", "description":"支点を表示"},
                       {"name":"PLOAD", "description":"節点外力を表示"}];
    $scope.results  = [{"name":"STRESS", "description":"部材応力を表示"},
                       {"name":"FORCE", "description":"節点荷重を表示"},
                       {"name":"DEFORMATION", "description":"変形図を描画"},
                       {"name":"DISP", "description":"変位を表示"},
                       {"name":"SRCANRATE", "description":"部材検定比を表示"},
                       {"name":"SRCANJOINT", "description":"接合部の検定比を表示"},
                       {"name":"DRIFT", "description":"部材変形角を表示"},
                       {"name":"RDISP", "description":"相対変位を表示"},
                       {"name":"REACTION", "description":"反力を表示"},
                       {"name":"ECCENTRIC", "description":"重心・剛心を描画"},
                       {"name":"STIFF", "description":"部材水平剛性を表示"}];
                       // {"name":"PRESSURE", "description":""},
                       // {"name":"YIELDRATIO", "description":""}];
    $scope.texts    = [{"name":"FONT", "description":"フォントサイズを設定"},
                       {"name":"POSITION", "description":"テキストの表示位置を設定"},
                       {"name":"ANCHOR", "description":"文字アンカー位置を設定"},
                       {"name":"PAGETITLE", "description":"ページタイトルを設定"},
                       {"name":"TITLE", "description":"タイトルを設定"},
                       {"name":"HEADER", "description":"ヘッダを設定"},
                       {"name":"TIMESTAMP", "description":"タイムスタンプを表示"},
                       {"name":"TEXT", "description":"テキストを設定"},
                       {"name":"TEXTBOX", "description":"テキストボックスを追加"},
                       {"name":"NAME_TEXTBOX", "description":"テキストボックスを表示"},
                       {"name":"INPUTFILE", "description":"入力ファイル名を表示"},
                       {"name":"OUTPUTFILE", "description":"出力ファイル名を表示"},
                       {"name":"VIEWPOINT", "description":"視点情報を表示"}];
    $scope.generals = [{"name":"PAGE", "description":"新しいページを開始"},
                       {"name":"FIGURE", "description":"新しい応力表示ページを開始"},
                       {"name":"MULTIPLE", "description":"1ページを複数に分割"},
                       {"name":"LOAD", "description":"別のfig2ファイルを読み込み"},
                       {"name":"READ", "description":"結果ファイルを読み込み"},
                       {"name":"FOR", "description":"指定範囲をfor文で繰返し"},
                       {"name":"NOFEED", "description":"改ページしない"},
                       {"name":"NOAXIS", "description":"全体座標系を非表示"},
                       {"name":"NOZERO", "description":"全体座標系の0を非表示"},
                       {"name":"NOCOLOUR", "description":"白黒表示"},
                       {"name":"NODATA", "description":"表示データ一覧を非表示"},
                       {"name":"NOLEGEND", "description":"凡例を非表示"}];
    $scope.colors   = [{"name":"COLOUR", "description":"断面の色で部材を描画"},
                       {"name":"SRCANCOLOR", "description":"検定比で色表示"},
                       {"name":"GREY", "description":"非表示部材をグレー表示"},
                       {"name":"PEN", "description":"ペンを追加"},
                       {"name":"NAME_PEN", "description":"指定したペンで描画"},
                       {"name":"MAXPEN", "description":"MAXで用いるペンを指定"},
                       {"name":"RAINBOW", "description":"レインボー表示"}];
    $scope.others   = [{"name":"UNIT", "description":"単位を設定"},
                       {"name":"KIJUN", "description":"基準線を描画"},
                       {"name":"NAME_KIJUN", "description":"指定した基準線平面の前後のみ表示"},
                       {"name":"KIJUNMOVE", "description":"基準線を上下に移動"},
                       {"name":"MEASURE", "description":"寸法を描画"},
                       {"name":"XMEASURE", "description":"X方向寸法を描画"},
                       {"name":"YMEASURE", "description":"Y方向寸法を描画"},
                       {"name":"ZMEASURE", "description":"Z方向寸法を描画"}];
}
